name: iogeo 
channels:
  - conda-forge
  - defaults
dependencies:

  - python=3.11
  
# STAPLES
  - autologging
  - numpy
  - pandas
  - sphinx
  - sphinx-rtd-theme

 # GEOSPATIAL ANALYSIS
  # - geopandas
  - geojson # used by pysheds
  - xarray # numpy arrays endowed with metadata, good e.g. for netCDF4 files
  # - bottleneck # speeds up NaN-skipping and rolling window aggregations by a large factor
  # - dask
      # Xarray integrates with Dask to support parallel computations
      # and streaming computation on datasets that don’t fit into memory. 
      # Currently, Dask is an entirely optional feature for xarray. 
      # However, the benefits of using Dask are sufficiently strong that Dask may 
      # become a required dependency in a future version of xarray.
  - rasterio # to read topography (ESRI ASCII, GEOTIFF and other formats)
  # - scikit-image # used by pysheds
  - netCDF4
  # - gdal # ('from osgeo import gdal' or from command line as installed with brew too)
  # - pygmt # it seems better to still use GMT from terminal...
